name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:
    secrets:
      secret:
        required: true
    outputs:
      set:
        value: ${{ jobs.check-secret.outputs.set }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
     - name: Check if secret is set
       id: check-secret
       run: |
          if [ "${{ secrets.secret }}" != "" ]; then
            echo "set=true" >> $GITHUB_OUTPUT
          fi
       shell: bash

     - name: Show result
       run: |
          echo "set: ${{ steps.check-secret.outputs.set }}"
       shell: bash

     - uses: actions/checkout@v4
     - name: Setup dotnet
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: 8.0.x
     - name: Build & Install
       run: dotnet build
     - name: Ensure browsers are installed
       run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
     - name: Run your tests
       run: dotnet test
