name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:
    secrets:
      secret:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
     - name: check MYSECRET exists
       env: 
            super_secret: ${{ secrets.MYSECRET }}
       if: ${{ env.super_secret == '' }}
       run: echo "echo the secret \"MY_SECRET\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"
     - uses: actions/checkout@v4
     - name: Setup dotnet
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: 8.0.x
     - name: Build & Install
       run: dotnet build
     - name: Ensure browsers are installed
       run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
     - name: Run your tests
       run: dotnet test
